// This file is auto-generated by Payload CMS.
// It maps component path#export keys → the actual imported components,
// allowing Payload's server-side renderer to resolve client/RSC components
// for the admin panel without dynamic imports at runtime.

import { RscEntryLexicalCell as a } from '@payloadcms/richtext-lexical/rsc'
import { RscEntryLexicalField as b } from '@payloadcms/richtext-lexical/rsc'
import { LexicalDiffComponent as c } from '@payloadcms/richtext-lexical/rsc'
import { AlignFeatureClient as d } from '@payloadcms/richtext-lexical/client'
import { BlockquoteFeatureClient as e } from '@payloadcms/richtext-lexical/client'
import { BoldFeatureClient as f } from '@payloadcms/richtext-lexical/client'
import { InlineCodeFeatureClient as g } from '@payloadcms/richtext-lexical/client'
import { ItalicFeatureClient as h } from '@payloadcms/richtext-lexical/client'
import { StrikethroughFeatureClient as i } from '@payloadcms/richtext-lexical/client'
import { SubscriptFeatureClient as j } from '@payloadcms/richtext-lexical/client'
import { SuperscriptFeatureClient as k } from '@payloadcms/richtext-lexical/client'
import { UnderlineFeatureClient as l } from '@payloadcms/richtext-lexical/client'
import { HeadingFeatureClient as m } from '@payloadcms/richtext-lexical/client'
import { HorizontalRuleFeatureClient as n } from '@payloadcms/richtext-lexical/client'
import { IndentFeatureClient as o } from '@payloadcms/richtext-lexical/client'
import { LinkFeatureClient as p } from '@payloadcms/richtext-lexical/client'
import { ChecklistFeatureClient as q } from '@payloadcms/richtext-lexical/client'
import { OrderedListFeatureClient as r } from '@payloadcms/richtext-lexical/client'
import { UnorderedListFeatureClient as s } from '@payloadcms/richtext-lexical/client'
import { ParagraphFeatureClient as t } from '@payloadcms/richtext-lexical/client'
import { RelationshipFeatureClient as u } from '@payloadcms/richtext-lexical/client'
import { InlineToolbarFeatureClient as v } from '@payloadcms/richtext-lexical/client'
import { UploadFeatureClient as w } from '@payloadcms/richtext-lexical/client'
import { SendNewsletterButton as x } from '@/components/admin/SendNewsletterButton'
import { CollectionCards as y } from '@payloadcms/next/rsc'

export const importMap = {
  "@payloadcms/richtext-lexical/rsc#RscEntryLexicalCell": a,
  "@payloadcms/richtext-lexical/rsc#RscEntryLexicalField": b,
  "@payloadcms/richtext-lexical/rsc#LexicalDiffComponent": c,
  "@payloadcms/richtext-lexical/client#AlignFeatureClient": d,
  "@payloadcms/richtext-lexical/client#BlockquoteFeatureClient": e,
  "@payloadcms/richtext-lexical/client#BoldFeatureClient": f,
  "@payloadcms/richtext-lexical/client#InlineCodeFeatureClient": g,
  "@payloadcms/richtext-lexical/client#ItalicFeatureClient": h,
  "@payloadcms/richtext-lexical/client#StrikethroughFeatureClient": i,
  "@payloadcms/richtext-lexical/client#SubscriptFeatureClient": j,
  "@payloadcms/richtext-lexical/client#SuperscriptFeatureClient": k,
  "@payloadcms/richtext-lexical/client#UnderlineFeatureClient": l,
  "@payloadcms/richtext-lexical/client#HeadingFeatureClient": m,
  "@payloadcms/richtext-lexical/client#HorizontalRuleFeatureClient": n,
  "@payloadcms/richtext-lexical/client#IndentFeatureClient": o,
  "@payloadcms/richtext-lexical/client#LinkFeatureClient": p,
  "@payloadcms/richtext-lexical/client#ChecklistFeatureClient": q,
  "@payloadcms/richtext-lexical/client#OrderedListFeatureClient": r,
  "@payloadcms/richtext-lexical/client#UnorderedListFeatureClient": s,
  "@payloadcms/richtext-lexical/client#ParagraphFeatureClient": t,
  "@payloadcms/richtext-lexical/client#RelationshipFeatureClient": u,
  "@payloadcms/richtext-lexical/client#InlineToolbarFeatureClient": v,
  "@payloadcms/richtext-lexical/client#UploadFeatureClient": w,
  "src/components/admin/SendNewsletterButton#SendNewsletterButton": x,
  "@payloadcms/next/rsc#CollectionCards": y,
}
